export const EXPENSE_CATEGORIES = [
  'comida',
  'transporte',
  'vivienda',
  'servicios',
  'salud',
  'educacion',
  'entretenimiento',
  'ropa',
  'suscripciones',
  'otros',
] as const

export const INCOME_CATEGORIES = ['sueldo', 'freelance', 'inversiones', 'regalo', 'otros'] as const

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number]
export type IncomeCategory = (typeof INCOME_CATEGORIES)[number]

export const CATEGORY_LABELS: Record<string, string> = {
  comida: 'Comida',
  transporte: 'Transporte',
  vivienda: 'Vivienda',
  servicios: 'Servicios',
  salud: 'Salud',
  educacion: 'Educación',
  entretenimiento: 'Entretenimiento',
  ropa: 'Ropa',
  suscripciones: 'Suscripciones',
  otros: 'Otros',
  sueldo: 'Sueldo',
  freelance: 'Freelance',
  inversiones: 'Inversiones',
  regalo: 'Regalo',
}

// TransactionType is what the user picks in the Movimientos form — 'transfer'
// is never user-selectable (see TransactionKind).
export type TransactionType = 'income' | 'expense'

// TransactionKind is the full set a Transaction can come back as — 'transfer'
// rows are generated by reload/contribution/card-transfer flows, never
// created directly, and never shown in Movimientos.
export type TransactionKind = TransactionType | 'transfer'

export type Frequency = 'weekly' | 'monthly' | 'yearly'

export const FREQUENCY_LABELS: Record<Frequency, string> = {
  weekly: 'Semanal',
  monthly: 'Mensual',
  yearly: 'Anual',
}

export interface Transaction {
  id: number
  type: TransactionKind
  amountCents: number
  category: string
  description: string
  date: string // YYYY-MM-DD
  cardId?: number
  fromCardId?: number
  toCardId?: number
  createdAt: string
}

export interface TransactionInput {
  type: TransactionType
  amountCents: number
  category: string
  description: string
  date: string
  cardId?: number
}

export interface Subscription {
  id: number
  name: string
  amountCents: number
  frequency: Frequency
  category: string
  nextBillingOn: string // YYYY-MM-DD
  active: boolean
  cardId?: number
  createdAt: string
}

export interface SubscriptionInput {
  name: string
  amountCents: number
  frequency: Frequency
  category: string
  nextBillingOn: string
  active: boolean
  cardId?: number
}

export interface Budget {
  id: number
  category: string
  monthlyLimitCents: number
  spentCents: number
}

export interface TrendPoint {
  month: string // YYYY-MM
  incomeCents: number
  expenseCents: number
}

export interface CategoryAmount {
  category: string
  amountCents: number
}

export interface FinanceSummary {
  balanceCents: number
  monthIncomeCents: number
  monthExpenseCents: number
  monthlyTrend: TrendPoint[]
  categoryBreakdown: CategoryAmount[]
}

export type CardType = 'debito' | 'credito' | 'prepago'

export const CARD_TYPE_LABELS: Record<CardType, string> = {
  debito: 'Débito',
  credito: 'Crédito',
  prepago: 'Prepago',
}

// balanceCents/usedCreditCents are computed by the backend from the
// transaction ledger, not stored — same shape as before, different source.
export interface Card {
  id: number
  name: string
  type: CardType
  bank: string
  last4: string
  color: string
  icon: string
  balanceCents: number
  creditLimitCents: number
  usedCreditCents: number
  createdAt: string
}

export interface CardInput {
  name: string
  type: CardType
  bank: string
  last4: string
  color: string
  icon: string
  initialBalanceCents?: number
  creditLimitCents?: number
}

export interface CardTransferInput {
  fromCardId: number
  toCardId: number
  amountCents: number
  date: string
  note: string
}

export interface TransactionFilters {
  month?: string
  type?: TransactionType
  category?: string
}

export const GOAL_ICONS = [
  'piggy-bank',
  'target',
  'plane',
  'home',
  'car',
  'graduation-cap',
] as const
export type GoalIcon = (typeof GOAL_ICONS)[number]

export const GOAL_COLORS = [
  '#10b981',
  '#3b82f6',
  '#f59e0b',
  '#ef4444',
  '#8b5cf6',
  '#06b6d4',
  '#ec4899',
  '#84cc16',
] as const
export type GoalColor = (typeof GOAL_COLORS)[number]

// defaultCardId is required — a goal always draws from a real card now,
// never a pure bookkeeping entry with no ledger effect.
export interface SavingsGoal {
  id: number
  name: string
  targetCents: number
  currentCents: number
  deadline?: string
  icon: string
  color: string
  defaultCardId: number
  createdBy: number
  createdAt: string
}

export interface SavingsGoalInput {
  name: string
  targetCents: number
  deadline?: string
  icon: string
  color: string
  defaultCardId: number
}

export interface SavingsContribution {
  id: number
  goalId: number
  amountCents: number
  date: string
  note?: string
  transactionId?: number
  createdBy: number
  createdAt: string
}

export interface SavingsContributionInput {
  amountCents: number
  date: string
  note?: string
}
